language: scala

dist: trusty

# required: until bug is fixed: https://github.com/travis-ci/travis-ci/issues/3259
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
      - google-chrome-stable
      - unzip

before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/

    # For selenium in headless linux system
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

scala:
   - 2.11.7
   - 2.11.8
   - 2.11.12
   - 2.12.7

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
