package vegas.DSL

import vegas.spec.Spec

object AxisDSL {

  def apply(labelAngle: OptArg[Double] = NoArg,
            format: OptArg[String] = NoArg,
            orient: OptArg[Spec.AxisOrient] = NoArg,
            title: OptArg[String] = NoArg,
            values: OptArg[List[Double]] = NoArg,
            axisWidth: OptArg[Double] = NoArg,
            layer: OptArg[String] = NoArg,
            offset: OptArg[Double] = NoArg,
            axisColor: OptArg[String] = NoArg,
            grid: OptArg[Boolean] = NoArg,
            gridColor: OptArg[String] = NoArg,
            gridDash: OptArg[List[Double]] = NoArg,
            gridOpacity: OptArg[Double] = NoArg,
            gridWidth: OptArg[Double] = NoArg,
            labels: OptArg[Boolean] = NoArg,
            labelAlign: OptArg[String] = NoArg,
            labelBaseline: OptArg[String] = NoArg,
            labelMaxLength: OptArg[Double] = NoArg,
            shortTimeLabels: OptArg[Boolean] = NoArg,
            subdivide: OptArg[Double] = NoArg,
            ticks: OptArg[Double] = NoArg,
            tickColor: OptArg[String] = NoArg,
            tickLabelColor: OptArg[String] = NoArg,
            tickLabelFont: OptArg[String] = NoArg,
            tickLabelFontSize: OptArg[Double] = NoArg,
            tickPadding: OptArg[Double] = NoArg,
            tickSize: OptArg[Double] = NoArg,
            tickSizeMajor: OptArg[Double] = NoArg,
            tickSizeMinor: OptArg[Double] = NoArg,
            tickSizeEnd: OptArg[Double] = NoArg,
            tickWidth: OptArg[Double] = NoArg,
            titleColor: OptArg[String] = NoArg,
            titleFont: OptArg[String] = NoArg,
            titleFontSize: OptArg[Double] = NoArg,
            titleFontWeight: OptArg[String] = NoArg,
            titleOffset: OptArg[Double] = NoArg,
            titleMaxLength: OptArg[Double] = NoArg,
            characterWidth: OptArg[Double] = NoArg,
            properties: OptArg[Spec.Axis.Properties] = NoArg) = {

    Spec.Axis(
      labelAngle = labelAngle,
      format = format,
      orient = orient,
      title = title,
      values = values,
      axisWidth = axisWidth,
      layer = layer,
      offset = offset,
      axisColor = axisColor,
      grid = grid,
      gridColor = gridColor,
      gridDash = gridDash,
      gridOpacity = gridOpacity,
      gridWidth = gridWidth,
      labels = labels,
      labelAlign = labelAlign,
      labelBaseline = labelBaseline,
      labelMaxLength = labelMaxLength,
      shortTimeLabels = shortTimeLabels,
      subdivide = subdivide,
      ticks = ticks,
      tickColor = tickColor,
      tickLabelColor = tickLabelColor,
      tickLabelFont = tickLabelFont,
      tickLabelFontSize = tickLabelFontSize,
      tickPadding = tickPadding,
      tickSize = tickSize,
      tickSizeMajor = tickSizeMajor,
      tickSizeMinor = tickSizeMinor,
      tickSizeEnd = tickSizeEnd,
      tickWidth = tickWidth,
      titleColor = titleColor,
      titleFont = titleFont,
      titleFontSize = titleFontSize,
      titleFontWeight = titleFontWeight,
      titleOffset = titleOffset,
      titleMaxLength = titleMaxLength,
      characterWidth = characterWidth,
      properties = properties)
 }

}

