name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Test
      uses: GabrielBB/xvfb-action@v1.6
      with:
        run: sbt test
